language: node_js
node_js:
- "8.2.1"

install:
- npm install 

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- npm run naughtyString
- npm run injectPwd
